/**
 * Root Layout Component
 * This wraps all pages in the application
 *
 * In Next.js App Router:
 * - layout.tsx defines the common structure for all pages
 * - It wraps around page.tsx components
 * - Only one RootLayout per app (at the root level)
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Font Configuration
 * Loads Google Fonts for use throughout the application
 */
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name
  subsets: ["latin"],             // Character set to load
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Page Metadata
 * Sets the HTML title and description for SEO
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout Component
 * The outermost wrapper for all pages
 *
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - The page content to render
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // suppressHydrationWarning on html and body prevents warnings
    // caused by browser extensions that modify these elements
    // (e.g., Grammarly, password managers add their own attributes)
    <html lang="en" suppressHydrationWarning>
      <body
        // Apply font variables to the body
        // antialiased makes fonts look smoother
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Render the page content */}
        {children}
      </body>
    </html>
  );
}
